# Generated by Django 5.0.6 on 2024-07-14 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cours', models.CharField(max_length=30)),
                ('img_cours', models.ImageField(default='Cours_img/default-cours.jpg', upload_to='Cours_img/')),
                ('file_cours', models.FileField(upload_to='Cours_file/')),
                ('note', models.CharField(default='0.0', max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_matiere', models.CharField(max_length=20)),
                ('img_matiere', models.ImageField(default='Matiere/default-matiere.jpg', upload_to='Matiere/')),
                ('nombre_cours', models.IntegerField(default=0, null=True)),
                ('level', models.CharField(choices=[('6e', '6e'), ('5e', '5e'), ('4e', '4e'), ('3e', '3e'), ('2nde', '2nde'), ('1ere', '1ere'), ('Tle', 'Tle')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_exercice', models.ImageField(default='exercice/default-exerice.jpg', upload_to='exercice/')),
                ('titre', models.CharField(max_length=50)),
                ('type_question', models.CharField(max_length=25)),
                ('questions', models.JSONField(default=None)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cours')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='de_matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.matiere'),
        ),
    ]
