# Generated by Django 5.0.6 on 2024-07-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='note',
        ),
    ]
